name: Ubuntu

on: 

  workflow_dispatch:

    inputs:

      code:

        description: 'Visit http://remotedesktop.google.com/headless and copy the command after Authentication'

        required: true

      pin:

        description: 'Enter a Pin (more or equal to 6 digits)'

        required: true

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Updates

      run: sudo apt update -y 

    - name: Installing Desktop Environment & Install files

      run: | 

        sudo apt install speedtest-cli



        



     

   

   

    - name: Done! You can see the machine in list now.

      run: bash loop.sh
